// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOBM3hxSYmdW7dbHkX6ACZ4haIfmHQK_8',
    appId: '1:826798997110:web:66d3c88b379bdf192ca957',
    messagingSenderId: '826798997110',
    projectId: 'firestore-8dcd1',
    authDomain: 'firestore-8dcd1.firebaseapp.com',
    storageBucket: 'firestore-8dcd1.appspot.com',
    measurementId: 'G-8R80R5NMQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnTFD3ZAQUQ2BxjnI0qlufmJ6Qrz7gZU8',
    appId: '1:826798997110:android:bf02eeab5ef0ae232ca957',
    messagingSenderId: '826798997110',
    projectId: 'firestore-8dcd1',
    storageBucket: 'firestore-8dcd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgDdKvoBJI5bBv7uDM87B9LDw452crPGI',
    appId: '1:826798997110:ios:6b29c94d5cfd60192ca957',
    messagingSenderId: '826798997110',
    projectId: 'firestore-8dcd1',
    storageBucket: 'firestore-8dcd1.appspot.com',
    iosClientId: '826798997110-t6m132176s3r04eil7gnf0at458si8pq.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgDdKvoBJI5bBv7uDM87B9LDw452crPGI',
    appId: '1:826798997110:ios:6b29c94d5cfd60192ca957',
    messagingSenderId: '826798997110',
    projectId: 'firestore-8dcd1',
    storageBucket: 'firestore-8dcd1.appspot.com',
    iosClientId: '826798997110-t6m132176s3r04eil7gnf0at458si8pq.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleAuth',
  );
}
